version: '2'
services:
    parinogroupapp-app:
        image: parinogroupapp
        external_links:
            - parinogroupapp-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/parinogroupapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    parinogroupapp-mysql:
        extends:
            file: mysql.yml
            service: parinogroupapp-mysql
